//Home Screen
export const GET_HOME_MOVIE_LIST_SUCCESS = 'GET_HOME_MOVIE_LIST_SUCCESS';
export const START_GET_HOME_MOVIE_LIST = 'START_GET_HOME_MOVIE_LIST';
export const GET_HOME_MOVIE_LIST_FAILURE = 'GET_HOME_MOVIE_LIST_FAILURE';

//Movie Screen
export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS';
export const START_GET_MOVIE_LIST = 'START_GET_MOVIE_LIST';
export const GET_MOVIE_LIST_FAILURE = 'GET_MOVIE_LIST_FAILURE';

//Movie Screen
export const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS';
export const START_GET_MOVIE_DETAIL = 'START_GET_MOVIE_DETAIL';
export const GET_MOVIE_DETAIL_FAILURE = 'GET_MOVIE_DETAIL_FAILURE';